### ISSUE TITLE
Doesn't seem to work with WorldEnvironment

### ISSUE THREAD

**Issue by raffomania** [BastiaanOlij/godot-sky-asset#2]
I added a WorldEnvironment to my scene and hooked the `sky_updated` signal up with this function:
```
func _on_Sky_texture_sky_updated():
	$Sky_texture.copy_to_environment($WorldEnvironment)
```
I get the following error:
```
Invalid get index 'background_sky' (on base: 'WorldEnvironment').
```
This happens in sky_texture.gd line 65.

**Comment by raffomania** [comment]
Just found out I need to pass `$WorldEnvironment.environment`. Could have thought of that :grin: Could you add a line to the readme explaining how to call `copy_to_environment` using a WorldEnvironment?
```
func _on_Sky_texture_sky_updated():
	$Sky_texture.copy_to_environment($WorldEnvironment.environment)
```

**Comment by BastiaanOlij** [comment]
Oops, yeah world environment is just a container node for the actual environment resource. I'll make a note of it in the asset thanks :)
