### ISSUE TITLE
Script Error with Godot 3.1 alpha build

### ISSUE THREAD

**Issue by glaforte** [BastiaanOlij/godot-sky-asset#4]
Hello! I have my own custom build of Godot 3.1 alpha build.
I download and imported the project. When I run it, I get a very white sky and a lot of light.
![image](https://user-images.githubusercontent.com/2227491/48925134-6611a800-ee8e-11e8-8973-effc4ec493cd.png)

I looked at the log and saw the following:
""
SCRIPT ERROR: (null): Invalid numeric constant
          At: :26
""
Do you think this issue could be related to my GLES3 drivers or Godot 3.1 alpha?

**Comment by BastiaanOlij** [comment]
Just fixed it, don't know why but Godot didn't like the 1e5 notation anymore.

**Comment by glaforte** [comment]
Thanks for fixing this! I'll have time to check it out in a few days :)
